title: TIOBE Sites Ranking
description: Static website displaying TIOBE's top 20 programming languages.
url: "https://jklrak.github.io"
baseurl: "" 

theme: jekyll-theme-swiss 
plugins:
  - jekyll-feed

markdown: kramdown
permalink: pretty
